version: '3'
networks:
  webservices:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
        # - gateway: 172.18.0.1
services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    networks:
      webservices:
        ipv4_address: 172.28.0.4
    ports:
      - "80:80"
    volumes:
      - .:/app/
    links:
      - php
  
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    networks:
      webservices:
        ipv4_address: 172.28.0.2
    volumes:
      - .:/app/
    links:
      - database
  
  database:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    # ports:
    #   - "3306:3306"
    networks:
      webservices:
        ipv4_address: 172.28.0.3
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    